# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-paginate

# Permalinks
permalink: pretty

# Setup
title: Yale Galaxy Lunch
tagline: 'Yale Galaxy Lunch'
description: 'Yale Galaxy Lunch Seminar Series'
url: https://yalegalaxylunch.github.io/
baseurl: "https://yalegalaxylunch.github.io/"

author:
  name: 'Chloe Neufeld'
  url: https://chloeneufeld.github.io

paginate: 1 # Only one post per page
paginate_path: "/page:num/"
